-- AlterTable
ALTER TABLE "point_usages" ALTER COLUMN "points_used" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "transactions" ALTER COLUMN "net_usd" SET DEFAULT 0,
ALTER COLUMN "net_usd" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "usd" SET DEFAULT 0,
ALTER COLUMN "usd" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "amount_usd" SET DEFAULT 0,
ALTER COLUMN "amount_usd" SET DATA TYPE DOUBLE PRECISION;
